language: rust
cache: cargo

matrix:
  include:
    - os: linux
      rust: nightly

    - os: osx
      rust: nightly

script:
  - rustup component add rust-src
  - cargo install -f xargo
  - cargo check
  - cargo test

branches:
  only:
    - master

notifications:
  email:
    on_success: never
